### ISSUE TITLE
@Override for createJSModules() causes build error with RN 4.8

### ISSUE THREAD

**Issue by burdiuz** [PeelTechnologies/react-native-os#5]
Hi!

I was trying to compile project with this library and got an error 
```
:react-native-os:compileReleaseJavaWithJavac
:react-native-os:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\www\my\ReactNativePlayground\node_modules\react-native-os\android\src\main\java\com\peel\react\RNOSModule.java:31: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-os:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-os:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
It seems that for now removing @ Override annotation is a workaround to successfully build the library.

**Comment by chriscohoat** [comment]
I have the same issue...since it happens every time I re-create `node_modules` I wrote a one line fix to remove the `@Override` at line 31:

```
cat node_modules/react-native-os/android/src/main/java/com/peel/react/RNOSModule.java | sed -e '31{/@Override/d;}' > RNOSModule.tmp.java && mv RNOSModule.tmp.java node_modules/react-native-os/android/src/main/java/com/peel/react/RNOSModule.java
```

Probably longer than it needs to be but it seems to work.

**Comment by filipemerker** [comment]
+1

**Comment by phillbaker** [comment]
Released version 1.2.0 on NPM which should fix this issue. I don't have contributor rights on this repo to close this issue, but support will be ongoing at https://github.com/aprock/react-native-os.

**Comment by akshay20jha** [comment]
> I have the same issue...since it happens every time I re-create `node_modules` I wrote a one line fix to remove the `@Override` at line 31:
> 
> ```
> cat node_modules/react-native-os/android/src/main/java/com/peel/react/RNOSModule.java | sed -e '31{/@Override/d;}' > RNOSModule.tmp.java && mv RNOSModule.tmp.java node_modules/react-native-os/android/src/main/java/com/peel/react/RNOSModule.java
> ```
> 
> Probably longer than it needs to be but it seems to work.

how you used this line where to put can you please tell me

**Comment by chriscohoat** [comment]
@akshay20jha I think the issue has been fixed by now but I believe I just ran the one-liner in the root of the directory when I needed it.
