### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [PeelTechnologies/react-native-os#9]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by phillbaker** [comment]
Hi @pacamara, I recently received access to update this package on NPM, but don't have access to this repo on github. We're going to be supporting this package at https://github.com/aprock/react-native-os. Would you mind open this issue there or maybe updating the source with a PR?

**Comment by pacamara** [comment]
Hi @phillbaker , thanks. A PR has now been opened for this upstream against react-native: https://github.com/facebook/react-native/pull/17747 

I'd suggest the gradle upgrade for react-native-os is postponed until such time that gets merged, please see discussion at https://github.com/react-native-community/react-native-svg/issues/581
